### ISSUE TITLE
Revisar los put*s secos, inútiles

### ISSUE THREAD

**Issue by gonzaleztroyano** [usuariomiguel/IAW2-BASH#1]
Dice el inútil de Raúl que le salen cosas extrañas, -e

**Comment by arrobadiaz** [comment]
Eres muy tontito, no? Pon público tu trabajo para poner pegas (◍•ᴗ•◍)✧*。

**Comment by usuariomiguel** [comment]
relajensen

**Comment by gonzaleztroyano** [comment]
> Bajensen 2 tonitos

Siguen sin solucionarse los echos! :/

**Comment by arrobadiaz** [comment]
Los ecos ya funcionan. Lo que no funciona ahora es el nombre que no le
gusta a apache :'-(

**Comment by gonzaleztroyano** [comment]
Lo mejor sería tener un documento plantilla y luego modificarlo utilizando el sed.

Pero de todas maneras, os dejo un ejemplo utilizando el echo. También es posible utilizar printf:

```
 ​        ​echo​ -e ​"​<VirtualHost *:80> \n ServerAdmin ​$1​@localhost \n ServerName blog.​$1​.iaw.com \n DocumentRoot /var/www/​$1​/blog \n ErrorLog /var/www/​$1​/ficheros/logs/blog.​$1​.iaw.com \n CustomLog //var/www/​$1​/ficheros/logs/blog.​$1​.iaw.com-access combined \n </VirtualHost> \n​"​ ​>​ /etc/apache2/sites-available/wp_​$1​.conf
```
